// Generated by Paste JSON as Code extension from https://quicktype.io page.
// Instruction: Copy the response in the clipboard (from Postman) and press f1 and select "Paste JSON as Code"

export interface PokemonListResponse {
  count: number;
  next?: string;
  previous?: string;
  results: SmallPokemon[];
}

export interface SmallPokemon {
  name: string;
  url: string;
  id: number;
  img: string;
}
